#!/bin/bash
# 导出固定的帧 可输入轨迹中的第一帧，即0 ps时的结构，通过“-dump”可指定时间，单位为ps
gmx trjconv -s ../md.tpr -f fit.xtc -n ../index.ndx -o pro.pdb -dump 0
# gmx trjconv -s ../md.tpr -f fit.xtc -n ../index.ndx -o protein.pdb -dump

R <<EOF
library("bio3d")
dcd <- read.dcd("pro.dcd")
pdb <- read.pdb("pro.pdb")
ca.inds <- atom.select(pdb, elety="CA")
xyz <- fit.xyz(fixed=pdb$xyz, mobile=dcd, fixed.inds=ca.inds$xyz,mobile.inds=ca.inds$xyz)
print(dim(xyz) == dim(dcd))

cij <- dccm(xyz[,ca.inds$xyz])
png("pca_corr.png", width=5000,height=4000, res=600)
plot(cij)
dev.off()

pc <- pca.xyz(xyz[,ca.inds$xyz])
png("pca_pc.png", width=5000,height=4000, res=600)
plot(pc, col=bwr.colors(nrow(xyz)))
dev.off()

print("all done ! good day ! ")
EOF
