#!/bin/bash
gmx pdb2gmx -f protein.pdb -o protein.gro -p topol.top -ignh << EOF
2
1
EOF

gmx genrestr -f lig.gro -o posre_lig.itp << EOF
0
EOF

cp protein.gro complex.gro

python <<EOF
with open('lig.gro') as f:
    lig_gro = f.readlines()

f.close()

with open('complex.gro') as f:
    complex_gro = f.readlines()

f.close()

lig_gro = lig_gro[2: -1]

complex_gro = complex_gro[:-1] + lig_gro + [complex_gro[-1]]

complex_gro[1] = str(int(complex_gro[1]) + len(lig_gro)) +'\n'

with open('complex.gro', 'w') as f:
    for i in complex_gro:
        f.write(i)

f.close()
EOF

python <<EOF
with open('lig.itp') as f:
    lista = f.readlines()

f.close()

str1 = '\n; Ligand position restraints\n#ifdef POSRES\n#include "posre_lig.itp"\n#endif\n'

lista = lista + [str1] 

with open('lig.itp', 'w') as f:
    for i in lista:
        f.write(i)

f.close()
EOF

python <<EOF
with open('topol.top') as f:
    lista = f.readlines()

f.close()

str1 = '; Include ligand topology\n#include "lig.itp"\n\n'
str2 = 'lig    1\n'
 
lista = lista[:22] + [str1] + lista[22:]+ [str2]

with open('topol.top', 'w') as f:
    for i in lista:
        f.write(i)

f.close()
EOF
gmx editconf -f complex.gro -o complex_box.gro -c -d 1.0 -bt cubic

gmx solvate -cp complex_box.gro -o complex_SOL.gro -p topol.top

gmx grompp -f em.mdp -c complex_SOL.gro -p topol.top -o em.tpr -maxwarn 2

gmx genion -s em.tpr -p topol.top -o system.gro -neutral 


gmx grompp -f em.mdp -c system.gro -p topol.top -o em.tpr
gmx mdrun -ntmpi 1 -ntomp 8 -v -deffnm em

gmx grompp -f pr.mdp -c em.gro -p topol.top -r em.gro -o pr.tpr
gmx mdrun -ntmpi 1 -ntomp 8 -v -deffnm pr

gmx make_ndx -f pr.gro #<< EOF
#1 | 13

#!24

#name 24 protein_lig

#name 25 envir

#q
#EOF

gmx grompp -f md.mdp -c pr.gro -p topol.top -o md.tpr -n index.ndx -maxwarn 10

gmx mdrun -ntmpi 1 -ntomp 8 -pin on -pinoffset 0 -pinstride 1 -pme gpu -deffnm md -v -gpu_id 0 


# 两次都选backbone
# -tu：输出横坐标为以ns为单位，不加默认以ps为单位
# 第一次选backbone，第二次选mol，代表结构对蛋白骨架做叠合，但只计算mol的RMSD，由此考察配体分子的rmsd
# 两次都选mol，则计算ligand的rmsd

#gmx rms -s md.tpr -f md.xtc -o RMSD-ligfitbackbone.xvg -tu ns #<< EOF
#4
#13
#EOF



